home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
  url('',views.index,name = 'index')
]

josho/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
import video
import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('home.urls')),
    path('video/',include('video.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'video'

urlpatterns = [
    url('^$', views.index,name = 'index'),
    url('^video list/$',views.video_list,name='videolist'),
    url('^add/$',views.form,name='add'),
    url('^(?P<play_id>.+)/$',views.details,name='details'),
    url('^(?P<play_id>.+)/favorite$',views.favorite,name='favor'),
    url('^add/save$',views.addform,name='form'),
    url('^playlist/update$',views.PlaylistUpdate.as_view(),name='update'),
    
    
]

home/models.py
from django.db import models

# Create your models here.

video/models.py
from django.db import models
from django.urls import reverse

class Playlist(models.Model):
    main_character = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)
    logo = models.FileField()

    def get_absolute_url(self):
        return reverse('video:index')

    def __str__(self):
        return self.main_character + ' - ' + self.genre
    


class Moviename(models.Model):
    playlist = models.ForeignKey(Playlist,on_delete=models.CASCADE)
    movie = models.CharField(max_length=1000)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.movie

home/views.py
from django.shortcuts import render
from django.http import HttpResponse,Http404
from django.template import Template

# Create your views here.
def index(request):
    return HttpResponse("<h1>Welcome to Jaykay Website Home Page<h1>")

video/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse, Http404
from django.template import loader
from .models import Playlist,Moviename
from django.views.generic.edit import UpdateView

def index(request):
    playlist = Playlist.objects.all()
    template = loader.get_template('video/index.html')
    playlists = {'playlist':playlist}
    
    return render(request,'video/index.html',{'playlist':playlist})
def details(request,play_id):
    play = get_object_or_404(Playlist,main_character = play_id)
    return render(request,'video/details.html',{'play':play})
def favorite(request,play_id):
    play = get_object_or_404(Playlist,main_character = play_id)
    vid = request.POST['video']
    vido = Moviename.objects.get(movie = vid)
    vido.is_favorite = True
    vido.save()
    return render(request,'video/details.html',{'play':play})
def video_list(request):
    vid = Moviename.objects.all()
    return render(request,'video/videoslist.html',{'vid':vid})
def form(request):
    return render(request,'video/playlistform.html',{'none':'none'})
def addform(request):
    vid = Playlist()
    vid.main_character = request.POST['actor']
    vid.genre = request.POST['genre']
    vid.logo = request.POST['logo']
    vid.save()
    return redirect('/video/')
class PlaylistUpdate(UpdateView):
    model = Playlist()
    fields = ['main_character','genre','logo']

video/templates/video/album_form.html
{% extends 'video/base.html'%}
{% load static %}
{% block body %}
<div>
    <div class="container form-wrapper">
        <h1 class="form-header">Update Playlist</h3>
    <form action="{% url 'video:form' %}" method="POST">
        {% csrf_token %}
        {% for f in fields %}
        <div class="form-group col-md-12">
            <label>{{f.label}}</label>
            {{f}}
        </div>
       {% endfor %}
        <input type="submit" value="Create" class="btn btn-block btn-success">
    </form>
    </div>
</div>
{% endblock %}

video/templates/video/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Stencil+Text:wght@300&display=swap" rel="stylesheet">    
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'music/style.css' %}">
<link rel="icon" href="{% static 'music/images/icon.png'%}">
    <title>{%block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{%url 'index' %}"><span class="fonti">Vivido</span> </a>
          </div>
      
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'video:index'%}"><span class="glyphicon glyphicon-cd"></span>&nbsp; Playlist</a></li>
              <li><a href="{%url 'video:videolist' %}"><span class="glyphicon glyphicon-film"></span>&nbsp; Video</a></li>
            </ul>
            <form class="navbar-form navbar-left">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{%url 'video:add' %}"><span class="glyphicon glyphicon-plus"></span>&nbsp; Add Playlist</a></li>
             <li><a href="#"><span class="glyphicon glyphicon-off"></span>&nbsp; Logout</a></li>
                </ul>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
      {% block body %}
      {% endblock %}
</body>
</html>

video/templates/video/details.html
{% extends 'video/base.html'%}
{% load static %}
    <title>{%block title%}Details for {{play.main_character}} - {{play.genre}} Movies {% endblock %}</title>

{% block body%}
<h1 style="margin-bottom: 20px;">Details of Movie with Id : {{play.id}}</h1>



<div class="row">
<div class="col-md-5 detail-pic">
<img src="{{play.logo.url }}" height="200" width="200"><br>
<a href="#" class="play-icon"><button class=" btn btn-default glyphicon glyphicon-trash"></button></a>
<a href="#" class="play-icon" ><button class=" btn btn-default glyphicon glyphicon-star"></button></a>
<span>{{play.main_character}}</span><br>
<span>{{play.genre}}</span>
</div>
<div class="col-md-7 detail-list">
    <a href="#"><button class="btn btn-primary" style="float: right;">Add New Movie</button></a>
    <form action="{% url 'video:favor' play.main_character %}" method="post" style="clear: both;">
        {% csrf_token %}
        {% for pay in play.moviename_set.all %}
        <input type="radio" name="video" id="{{pay.movie}}" value="{{pay.movie}}">
        <label for="{{pay.movie}}">{{pay.movie}}</label>
        {% if pay.is_favorite %}
        <span class="glyphicon glyphicon-heart"></span>
        {% else %}
        <span class="glyphicon glyphicon-heart-empty"></span>
        {% endif %}<br>
        {% endfor %}
        <input type="submit" value="Submit" class="btn btn-success">
       
    </form>
</div>
</div>


{% endblock %}

video/templates/video/index.html
{% extends 'video/base.html' %}
{% load static %}

{% block body%}
    <h1 id="index-header">
        List of JAykay Video Library
    </h1>
    <div class="container">
    <div  class="row">
        {% if playlist %}
        {%for play in playlist%}
       
          
            <a href="{% url 'video:details' play.main_character%}">
              <div class="col-md-4 col-sm-12">
                <img src="{{play.logo.url}}" height="200" width="200"><br>
                <span>{{play.main_character}}</span>
              </div>
            </a>
            
       
        {% endfor %}
        {% else %}
        <p><b>NO</b> PLaylist Found</p>
        {% endif %}
    </div>
  </div>
{% endblock %}

video/templates/video/playlistform.html
{% extends 'video/base.html'%}
{%block title%}Add Playlist{% endblock %}
{%block body %}
<div class="container form-wrapper">
    <h1 class="form-header">Create Playlist</h3>
<form action="{% url 'video:form' %}" method="POST">
    {% csrf_token %}
    <div class="form-group col-md-12">
        <label>Playlist Name</label>
        <input type="text" name="actor" class="form-control" value="">
    </div>
    <div class="form-group col-md-12">
        <label>Genre</label>
        <input type="text" name="genre" class="form-control" value="">

    </div>
    <div class="form-group col-md-12">
        <label>Playlist Image</label>
        
        <input type="file" name="logo" class="form-control" >
    </div>
    <input type="submit" value="Create" class="btn btn-block btn-success">
</form>
</div>
{% endblock%}

video/templates/video/videoslist.html
{% extends 'video/base.html'%}
{% block title %}
List of Videos
{% endblock %}
{% block body %}
<ul>
    {% for v in vid %}
    <li class="movie-list">{{v.movie}}</li>
    {% endfor %}
</ul>
{% endblock %}